[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python -m nltk.downloader punkt"
watchPaths = ["app/**", "utils/**", "config/**", "requirements.txt", "*.py"]

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
ENV = "prod"
LANGFUSE_ENABLED = "true"
LANGFUSE_SAMPLING_RATE = "0.1"
EMBEDDING_BACKEND = "openai"
