[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python3 startup-simple.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
ENV = "prod"
LANGFUSE_ENABLED = "true"
LANGFUSE_SAMPLING_RATE = "0.1"
