name: Smart Deploy

on:
  push:
    branches: [main]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'app/**'
              - 'utils/**'
              - 'config/**'
              - 'requirements.txt'
              - 'railway.toml'
            frontend:
              - 'ui/**'

  deploy-backend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway Deploy
        run: |
          echo "Backend changes detected - Railway will auto-deploy"

  deploy-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: |
          echo "Frontend changes detected - Vercel will auto-deploy"
